### ISSUE TITLE
Compilation on 32-bit

### ISSUE THREAD

**Issue by miloyip** [taocpp/json#1]
We found that in nativejson-benchmark, while building in 32-bit mode, it generates this static assertion failure.

~~~
../../thirdparty/taocppjson/include/tao/json/internal/asserts.hh:16:1: error: static_assert failed "internal consistency"
static_assert( sizeof( signed long ) == 8, "internal consistency" );
^              ~~~~~~~~~~~~~~~~~~~~~~~~~~
../../thirdparty/taocppjson/include/tao/json/internal/asserts.hh:17:1: error: static_assert failed "internal consistency"
static_assert( sizeof( unsigned long ) == 8, "internal consistency" );
^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~

**Comment by ColinH** [comment]
Right, hadn't tried that yet. I just made a small update that should fix 32bit compatibility. My test coverage isn't complete, but the already included tests now work in both 32bit and 64bit. Hope that does the trick...
