### ISSUE TITLE
tao::json::to_string prints out values in reverse

### ISSUE THREAD

**Issue by lawrence-koh** [taocpp/json#100]
Hi, I noticed that the to_string function appears to print out json key_value pairs in reverse. 

e.g. 

```
   tao::json::value json_value; 
   json_value.emplace( "key_a", "value_a" );
   json_value.emplace( "key_b", "value_b" );
   json_value.emplace( "key_c", "value_c" );
   std::string output_string = tao::json::to_string( json_value, 2 );
```

output_string becomes: `"{\n  \"key_c\": \"value_c\",\n  \"key_b\": \"value_b\",\n  \"key_a\": \"value_a\"\n}"`

Could I check if there is a proper way to use the library functions such that the data will be printed out in sequence please?

**Comment by d-frey** [comment]
Are you sure that the above holds true? I mean, we do use `std::map` to hold the key-value pairs, so they are sorted. But in the above the order should be `key_a`, `key_b` and `key_c`, independent of the order in which they were inserted.

**Comment by lawrence-koh** [comment]
Hi Daniel, apologies I now realise that the example doesn't hold true. What I meant to enquire was whether it is possible for the key-value pairs to be printed out in the same order as they were emplaced e.g. 
```
   tao::json::value json_value; 
   json_value.emplace( "foo", "foo_value" );
   json_value.emplace( "baz", "baz_value" );
   json_value.emplace( "bar", "bar_value" );
   std::string output_string = tao::json::to_string( json_value, 2 );
```
the to_string function to print out foo, baz and bar in the same order they were emplaced rather than sorting them to bar, baz and foo. 

The reason is that I am trying to create a json output file and would like to have the key-value pairs to retain the order of emplacement.

I suppose that is not possible given that, as you have clarified, the underlying implementation is `std::map`?

**Comment by d-frey** [comment]
No, that is currently not possible. The events API, of course, does not reorder events but the value class always uses a (sorted) container, as reordering key-value pairs is allowed by the JSON spec and yields an equivalent value.

**Comment by lawrence-koh** [comment]
got it. I will take a stab at the events API then. Thanks Daniel!
