### ISSUE TITLE
Better way to read value only if it exists?

### ISSUE THREAD

**Issue by hoytech** [taocpp/json#104]
Hi! I'm frequently writing the following bit of code:

    uint64_t limit = 10;
    if (query.optional<uint64_t>("limit")) query.to(limit, "limit");

Is there a less verbose way? Maybe something like this:

    uint64_t limit = 10;
    query.to_if_exists(limit, "limit");

Thanks in advance for your advice!

**Comment by d-frey** [comment]
You can use

```c++
const auto limit = query.optional< uint64_t >( "limit" ).value_or( 10 );
```

See https://en.cppreference.com/w/cpp/utility/optional/value_or

**Comment by hoytech** [comment]
Ahhh I didn't know about value_or.

That's a good solution -- thank you, I appreciate it!
