### ISSUE TITLE
Create new Beta Release

### ISSUE THREAD

**Issue by d-frey** [taocpp/json#107]
As a reminder to ourselves: We should release a new version of the PEGTL (with latest small changes from Colin), update taoJSON's submodule, then create a new Beta Release and packages for Conan etc. soon-ish. Uilian: Note that this will be a package depending on the PEGTL package, as we do not copy the source from PEGTL into taoJSON anymore.

**Comment by uilianries** [comment]
> update taoJSON's submodule

That's new for me, I didn't know Tao JSON depends on PEGTL

**Comment by d-frey** [comment]
That's why I'm mentioning it. Of course, if a suitable PEGTL is found in the system that should also be picked up. The submodule is mostly needed for the CI jobs and development. But taoJSON is now a library depending on another library, the PEGTL. In the "good old days" we had an embedded PEGTL as part of taoJSON, but as we also created taoCONFIG which then depended on taoJSON, we decided to change that and do it the "proper" way. Yeah, all pretty subjective, so feedback is welcome :)

**Comment by uilianries** [comment]
Well, as Conan maintainer, I'll say to avoid git submodule and use Conan instead, but old school users will disagree and say Git submodule is fine (which is true). Anyway, we can offer both and people decide what pick up.

And about version alignment, latest PEGTL version or newest commit should be enough, or do you thing about keep specific TaoJSON release aligned with another PEGTL release?

**Comment by d-frey** [comment]
The Conan package for taoJSON should depend on the Conan package for PEGTL, sure. Submodules, as mentioned, are a fallback if no suitable system package is found. But all package systems should provide a suitable PEGTL version as dependency.

The upcoming taoJSON beta.13 should probably depend on PEGTL 3.2.0+, that should be good enough. We will check the actual minimum required version of PEGTL when we get to it. I'm still way to busy with taoPQ currently and Colin is also busy with personal stuff, so this whole thing might take a couple days still.

**Comment by ColinH** [comment]
@uilianries Do you need anything more than a new tag to make new Conan packages?

**Comment by uilianries** [comment]
Hello, only tags are enough. I'll a Conan PR as soon as we have the new
tag. I can do it today later. Have a great Sunday!

**Comment by ColinH** [comment]
Great, the little extension to the binding facilities from earlier does not work with the Microsoft compiler. Since both GCC and Clang accept the code it's probably something not implemented yet, but I'll have to check. @uilianries Thanks, have a great day, too!

**Comment by ColinH** [comment]
After implementing the straightforward workaround for MSVC, and polishing and testing that corner of the binding facilities a bit more, I just tagged 1.0.0-beta.13, @uilianries if you can do the honours and create the new packages... Thank you!

**Comment by ColinH** [comment]
Actually hold that thought, @d-frey we still need to update the PEGTL dependency?

**Comment by d-frey** [comment]
The submodule is for the CI jobs and for people that don't install the PEGTL in their system. If the submodule references a version from the PEGTL repo that is good enough for taoJSON, there is no direct need for an upgrade.

The goal of the packaging should be to ignore the submodule and instead have a dependency on a PEGTL package that will then be used by taoJSON. For that, we should simply require PEGTL >= 3.2.0, as I don't think that taoJSON requires any feature/bugfix from newer versions, right?

**Comment by uilianries** [comment]
Hello! I just pushed a PR with the new release for Conan: https://github.com/conan-io/conan-center-index/pull/7397

**Comment by gsantner** [comment]
Hello!

I wanted to ask if a new (beta) release could be tagged? The current tagged version is from 2023 and there have been a few unreleased fixes and improvements since that [(overview)](https://github.com/taocpp/json/compare/1.0.0-beta.14...main).

Of course, if the master is somewhat fine (as there are failed CI build marks)  
![Image](https://github.com/user-attachments/assets/8dbdd085-82fc-4589-9983-ff0e00c5a960)

Also, would it make sense to make it a normal (non-beta) release? I found #135 but since few years/2023 didn't were the years of radical reworks I assume taojson will roughly stay the same.
