### ISSUE TITLE
binding of member functions of custom type

### ISSUE THREAD

**Issue by assafcohen** [taocpp/json#108]
hi, 
I have a simple struct that has a data member that needs to be processed by a function when assigning it to tao::json::value.
```
struct my_type{
   std::string str_;
   int i_;
};
  std::string do_somthing_with_i_()
{
    return std::to_string(i_*i_);
}
template<>
struct
	tao::json::traits<my_type>
	: binding::object<

		TAO_JSON_BIND_REQUIRED("II", &do_somthing_with_i_),
		,TAO_JSON_BIND_REQUIRED("", &my_type::str_)>{};
```
what is the proper way to achieve this kind of behavior?
thank you for a fantastic library.

**Comment by ColinH** [comment]
Hi, the parts that allow for this are still a bit work-in-progress, however there wasn't that much missing to get at least one or two simple cases up-and-running. If you check out the commit above you will see a new test source that shows how you cat use a custom function to access a field (or computed field).

**Comment by assafcohen** [comment]
Thank you, works great

**Comment by ColinH** [comment]
With commit 1a7fa4a34696d105fe1a10297eaceaf48a7fa403 you are no longer forced to use or not use noexcept on the accessor functions.
