### ISSUE TITLE
Schema Validation Failure Reason

### ISSUE THREAD

**Issue by maierlars** [taocpp/json#111]
I am huge fan of tao-json! Great work! To make tao-json even better it would be super awesome if the schema validation could report more than just `true/false`, or `valid/invalid`. Additionally, it could provide the path to the invalid field and a short string explaining the error (something like: `expected number`) or a error code, like `kExpectedNumber`.

**Comment by ColinH** [comment]
Thank you! Unfortunately generating good error messages is often really hard, much harder than it might seem from the outside, and we will only start investing the necessary time when everything else is sufficiently stable (in the sense of "no braking changes", not in the sense of "works without crashing"; taoJSON is quite reliable in what it does) for a proper 1.0.0 which, given how many new ideas we have, is, realistically speaking, still years away. But as always, patches are welcome!
