### ISSUE TITLE
CMake imported target is not `taocpp::json` anymore

### ISSUE THREAD

**Issue by SpaceIm** [taocpp/json#114]
https://github.com/taocpp/json/commit/47edc2f9e29f8b84bbbe68c2ccf64aacb8e2fa10 has changed logical target name from `json` to `taocpp-json`. But it also changes imported target name as a side effect, which is not `taocpp::json` anymore (like the ALIAS target which did not change), but `taocpp::taocpp-json`.

To avoid breaking change in imported target name, you should add to CMakeLists:

```cmake
set_target_properties(taocpp-json PROPERTIES EXPORT_NAME json)
```

https://cmake.org/cmake/help/latest/prop_tgt/EXPORT_NAME.html

**Comment by d-frey** [comment]
I never really understood how this works. If the library is called "json" or the export name is "json" - wouldn't that lead to clashes in other projects that depend on multiple JSON libraries if they all use "json" as their CMake name? How does CMake handle this? I understand putting json into a namespace taocpp::, but the top-level names should be unique, no? And wouldn't your suggestion introduce "json" as a top-level name again?

**Comment by SpaceIm** [comment]
No, logical target would still be `taocpp-json`, but imported target would be `taocpp::json`, so no clash with a `json` target.
