### ISSUE TITLE
How to write cbor/jaxn/msgpack and other file ?

### ISSUE THREAD

**Issue by meftunca** [taocpp/json#116]
How to write cbor/jaxn/msgpack and other file ?

Hello, I am trying to increase my c++ competencies. I'm currently writing a simple database to satisfy my performance curiosity and dealing with binary format files. Can you tell me how can I create it?

**Comment by ColinH** [comment]
How to create a CBOR or MessagePack file depends a bit on the data that you want to write, or, more precisely, on the in-memory representation of that data.

If you already have a `tao::json::value` and want to write that e.g. as CBOR you can convert it to a `std::string` via the function in `tao/json/cbor/to_string.hpp` and write that to a file, or directly serialise to an appropriately set up `std::ostream` via the function in `tao/json/cbor/to_stream.hpp`.

Or you could use the corresponding functions in the `events` sub-directories where the Events consumers `to_string` and `to_stream` give you a more low-level access to the functions that generate CBOR etc. output.
