### ISSUE TITLE
How can we improve tao-json performance ?

### ISSUE THREAD

**Issue by meftunca** [taocpp/json#118]
Processing large data like 'Simdjson' is not my main goal. But I am working on a machine learning based database and I need high performance. Right now it works like 143mb/s with insufficient efficiency for me. My goal is to reach (>=)800mb/s processing efficiency.

# Device features I tested:

CPU: intel i7 9750h 6 cores 12 threads min> 2.6ghz ~ 4.5ghz < max

Ram capacity: 32gb 2400mhz

SSD capacity: 512gb samsung 980

**Comment by d-frey** [comment]
The question is what parts of our library you are using and where the bottlenecks are. Given the modular design of taoJSON, you could use simdjson as a parser (or any other parser) and feed events from that parser to our events interface, hence making use of all the other parts our library offers. Start by adding benchmarks and profiling to your code and make sure you focus on the parts that are most relevant.
