### ISSUE TITLE
transforming unsigned to chrono::duration

### ISSUE THREAD

**Issue by assafcohen** [taocpp/json#119]
I was wondering what's the proper way of serialize/deserialize an object with std::chrono::duration as data member.
Thank you

**Comment by d-frey** [comment]
You can register data types with the type traits, see https://github.com/taocpp/json/blob/main/doc/Type-Traits.md

**Comment by assafcohen** [comment]
Thank you for your reply, it seems that chrono::duration d

**Comment by assafcohen** [comment]
thank you very much, it seems that I has an issue on my end
