### ISSUE TITLE
Make array from existing vector

### ISSUE THREAD

**Issue by DraTeots** [taocpp/json#12]
Hi!

If I have an existing vector, say

```c++
std::vector<int> example_vector{1, 2, 3, 4};
```

is it possible to create a json value from it other than making iterating ```emplace_back``` with for? 

```c++
tao::json::value::array foo(example_vector);   // error
```

**Comment by ColinH** [comment]
One possibility is to use the traits-class with a custom `assign()`-method:

```c++
template< typename T, typename V = void >
struct my_traits
   : public tao::json::traits< T, V >
{
};

template<>
struct my_traits< std::vector< int > >
{
   template< template< typename... > class Traits >
   static void assign( tao::json::basic_value< Traits >& v, const std::vector< int >& w )
   {
      v.prepare_array();
      for( const auto i : w ) {
         v.unsafe_emplace_back( i );
      }
   }
};
```
That way you only need the iteration once, and in all other places you can simply write:
```c++
   std::vector< int > v = { 1, 2, 3, 4 };
   tao::json::basic_value< my_traits > w( v );
```
Does this work for you?

There might be other solutions, but that's exactly why we have the traits-mechanism, to instantiate value-objects from anything that the user supplies an appropriate `assign()`-method for...

**Comment by d-frey** [comment]
The above could be further improved by adding

```cpp
v.unsafe_get_array().reserve( w.size() );
```

right after the `v.prepare_array();`.

**Comment by ColinH** [comment]
I'm closing this for now, feel free to reopen if something doesn't work or there are further questions.
