### ISSUE TITLE
Issues using 1.0.0-beta.13 with C++20

### ISSUE THREAD

**Issue by jarzec** [taocpp/json#131]
I was having issues using the most recent release tag (1.0.0-beta.13) with C++20.
A quick check seems to suggest that version form the `main` branch works well with C++20.
Is there a chance to get a new release tag on a version compatible with C++20?

**Comment by ColinH** [comment]
We'll tag a new version this week...

**Comment by JarekGlobus** [comment]
Thank you very much

**Comment by ColinH** [comment]
Sorry, things are taking a bit longer; we need to finish a couple of maintenance tasks before feeling comfortable tagging a new version.

**Comment by meftunca** [comment]
What is the latest situation?

**Comment by ColinH** [comment]
1.0.0-beta.14 is now available.
