### ISSUE TITLE
About the first stable version of Taojson

### ISSUE THREAD

**Issue by nmkoremblum** [taocpp/json#135]
Hi all

Excuse me if this question is duplicated, I couldn't find the answer.

Could you please provide us with any information about the release of the first stable version of taojson? Do you have any estimated timelines or release dates? Are you even still generating new beta releases?

Thanks in advance for your reply

**Comment by ColinH** [comment]
taoJSON is very stable in the sense that the existing functionality is generally well tested and we ourselves are using it in various places in production environments, including in the shape of our taoCONFIG library.

We just tagged a new beta release that consolidates a lot of minor improvements and fixes made over the past months.

The "issue" with reaching an official 1.0.0 is that, over time, we have many rather radical ideas on how to change and improve things, and it's not quite clear when we will get around to that.

For now you can assume that taoJSON works well and will not see any large changes in the near future.
