### ISSUE TITLE
simple json program won't compile on raspberry pi bullseye

### ISSUE THREAD

**Issue by johncblacker** [taocpp/json#137]
I have copied the tao/json and tao.pegtl directories into /usr/local/include/tao and tried compile this way:

g++ -std=c++17 readjsonfile.cpp -o readjsonfile -I /usr/local/include/tao

Here is my code:

#include <tao/json.hpp>
#include <tao/json/contrib/traits.hpp>

const tao::json::value v = tao::json::from_file("config.json");

cout<<v<<endl;

config.json is a simple json file.

Here is just a sample of the error output:

In file included from /usr/local/include/tao/json/internal/action.hpp:15,
                 from /usr/local/include/tao/json/events/from_file.hpp:7,
                 from /usr/local/include/tao/json/from_file.hpp:9,
                 from /usr/local/include/tao/json.hpp:11,
                 from readjsonfile.cpp:1:
/usr/local/include/tao/json/internal/grammar.hpp: In static member function ‘static bool tao::json::internal::rules::sor_value::match_number(Input&, States&& ...)’:
/usr/local/include/tao/json/internal/grammar.hpp:169:54: error: ‘dontcare’ is not a member of ‘tao::pegtl::rewind_mode’
  169 |                if( !match_zero< NEG, A, rewind_mode::dontcare, Action, Control >( in, st... ) ) {
      |                                                      ^~~~~~~~
/usr/local/include/tao/json/internal/grammar.hpp: In static member function ‘static bool tao::json::internal::rules::sor_value::match_impl(Input&, States&& ...)’:
/usr/local/include/tao/json/internal/grammar.hpp:195:71: error: ‘dontcare’ is not a member of ‘tao::pegtl::rewind_mode’
  195 |                if( in.empty() || !match_number< true, A, rewind_mode::dontcare, Action, Control >( in, st... ) ) {
      |                                                                       ^~~~~~~~
In file included from /usr/local/include/tao/json.hpp:15,
                 from readjsonfile.cpp:1:
/usr/local/include/tao/json/parts_parser.hpp: In static member function ‘static bool tao::json::internal::rules::double_rule::match_impl(Input&, States&& ...)’:
/usr/local/include/tao/json/parts_parser.hpp:79:88: error: ‘dontcare’ is not a member of ‘tao::pegtl::rewind_mode’
   79 |                      if( in.empty() || !sor_value::match_number< true, A, rewind_mode::dontcare, Action, Control >( in, st... ) ) {
      |                                                                                        ^~~~~~~~
In file included from /usr/local/include/tao/json/jaxn/internal/bunescape_action.hpp:14,
                 from /usr/local/include/tao/json/jaxn/internal/action.hpp:20,
                 from /usr/local/include/tao/json/jaxn/parts_parser.hpp:9,
                 from /usr/local/include/tao/json/jaxn/consume_file.hpp:14,
                 from /usr/local/include/tao/json/jaxn.hpp:9,
                 from /usr/local/include/tao/json.hpp:38,
                 from readjsonfile.cpp:1:
/usr/local/include/tao/json/jaxn/internal/grammar.hpp: In static member function ‘static bool tao::json::jaxn::internal::rules::sor_value_impl<String, Binary>::match_must(Input&, States&& ...)’:
/usr/local/include/tao/json/jaxn/internal/grammar.hpp:245:77: error: ‘dontcare’ is not a member of ‘tao::pegtl::rewind_mode’
  245 |             return Control< must< Rule > >::template match< A, rewind_mode::dontcare, Action, Control >( in, st... );
      |                                                                             ^~~~~~~~
/usr/local/include/tao/json/jaxn/internal/grammar.hpp: In static member function ‘static bool tao::json::jaxn::internal::rules::sor_value_impl<String, Binary>::match_number(Input&, States&& ...)’:
/usr/local/include/tao/json/jaxn/internal/grammar.hpp:302:54: error: ‘dontcare’ is not a member of ‘tao::pegtl::rewind_mode’
  302 |                if( !match_zero< NEG, A, rewind_mode::dontcare, Action, Control >( in, st... ) ) {
      |                                                      ^~~~~~~~
/usr/local/include/tao/json/jaxn/internal/grammar.hpp: In static member function ‘static bool tao::json::jaxn::internal::rules::sor_value_impl<String, Binary>::match_impl(Input&, States&& ...)’:
/usr/local/include/tao/json/jaxn/internal/grammar.hpp:336:72: error: ‘dontcare’ is not a member of ‘tao::pegtl::rewind_mode’
  336 |                if( in.empty() || !match_number< false, A, rewind_mode::dontcare, Action, Control >( in, st... ) ) {
      |                                                                        ^~~~~~~~
/usr/local/include/tao/json/jaxn/internal/grammar.hpp:343:71: error: ‘dontcare’ is not a member of ‘tao::pegtl::rewind_mode’
  343 |                if( in.empty() || !match_number< true, A, rewind_mode::dontcare, Action, Control >( in, st... ) ) {
      |                                                                       ^~~~~~~~
In file included from /usr/local/include/tao/json/jaxn/consume_file.hpp:14,
                 from /usr/local/include/tao/json/jaxn.hpp:9,
                 from /usr/local/include/tao/json.hpp:38,
                 from readjsonfile.cpp:1:
/usr/local/include/tao/json/jaxn/parts_parser.hpp: In static member function ‘static bool tao::json::jaxn::internal::rules::double_rule::match_impl(Input&, States&& ...)’:
/usr/local/include/tao/json/jaxn/parts_parser.hpp:36:89: error: ‘dontcare’ is not a member of ‘tao::pegtl::rewind_mode’
   36 |                      if( in.empty() || !sor_value::match_number< false, A, rewind_mode::dontcare, Action, Control >( in, st... ) ) {
      |                                                                                         ^~~~~~~~
In file included from /usr/local/include/tao/json/jaxn/consume_file.hpp:14,
                 from /usr/local/include/tao/json/jaxn.hpp:9,
                 from /usr/local/include/tao/json.hpp:38,
                 from readjsonfile.cpp:1:

What might be wrong?

g++ version 10.2.1 20210110

**Comment by ColinH** [comment]
If you use the latest taoJSON release and then the PEGTL from the submodule, i.e. the one in `external/PEGTL`, instead of checking out the main branch of the PEGTL, it should work.

**Comment by johncblacker** [comment]
I’m sorry, but I don’t see an “external/PEGTL” in the PEGTL repository on GITHUB; can you send me a link to it?  

Thank you very much.

**Comment by johncblacker** [comment]
In the json repository that I downloaded, the json/external/PEGTL subdirectory is empty…

 

Thanks. jb

**Comment by ColinH** [comment]
Did you issue a `git submodule init` and `git submodule update` in the taoJSON main directory?

**Comment by ColinH** [comment]
Ok, happy hacking!
