### ISSUE TITLE
Reset Event consumer?

### ISSUE THREAD

**Issue by rowlesmr** [taocpp/json#141]
Is there a way to reset an event consumer?

I'm parsing a custom data format, and building values as I go. I am able to get to a spot where I want to throw away some events I've gathered due to a data formatting error.

so I would (essentially) be doing something like:
```C++
tao::json::events::to_value consumer;
consumer.begin_object();
consumer.key( "a" );
consumer.number( 1.0 );
consumer.member();
consumer.key( "b" );

consumer.reset(); // or equivalent
```

As far as I can tell, the only way to do this is to dive into the implementation and
```C++
consumer.stack_.clear();
consumer.keys_.clear();
```
but then I can't see how to reset `value_`.

**Comment by d-frey** [comment]
You could use `consumer.value_.set_uninitialized()`. I'll also add a `reset()`-method now to do this conveniently, just give me a minute...

**Comment by rowlesmr** [comment]
Ta a lot! `.set_uninitialized()` was what I went to about 30 min later...
