### ISSUE TITLE
traits: ability to define what optional means

### ISSUE THREAD

**Issue by michael-brade** [taocpp/json#146]
Hi, here is another idea: right now there the possibility to define what "nothing" means by implementing `is_nothing` in a trait. However, this is applied to both `TAO_JSON_BIND_REQUIRED` and `TAO_JSON_BIND_OPTIONAL`. Would it be possible to limit it to `TAO_JSON_BIND_OPTIONAL`? Or is it possible to find another way to define what it means for a value to be optional? Sometimes I want to serialize a `false` value and sometimes I don't (need to). But I can only implement one `is_nothing` for `bool`.

**Comment by ColinH** [comment]
Am I right to assume that working with `std::optional< bool >` is not a viable work-around?

**Comment by michael-brade** [comment]
yes because that is an API change and it wouldn't be true. The object always has the bool (or int or string for that matter), it's just about how to serialize this object to json.

**Comment by ColinH** [comment]
Now I'm wondering whether we still need `for_nothing_value`.

**Comment by michael-brade** [comment]
Great, I agree with that so far. 

Yes, I like `for_nothing_value` because then I can at least somewhat individually decide if I want the 0/false/empty values in a json representation or not.

**Comment by ColinH** [comment]
After the most recent change `binding::object` encodes a member when the object uses `for_nothing_value::encode` _and/or_ the member uses `member_kind::required` _and/or_ the member's `is_nothing_value` is `false`.

Consequently `for_nothing_value` does _not_ influence the behaviour of `required` members. That sounds reasonable and I'm prone to believe that it can stay like this. @michael-brade Do you agree, does this work for your use cases?

```c++
template< typename A, template< typename... > class Traits, typename C >
[[nodiscard]] static bool require_encode( const C& x )
{
   return ( N == for_nothing_value::encode ) || ( A::kind == member_kind::required ) || ( !A::template is_nothing< Traits >( x ) );
}
```

**Comment by michael-brade** [comment]
Yes, I agree and the logic is very good. Thanks a lot!
