### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by toughengineer** [taocpp/json#148]
There are what looks like benchmarks in [/src/perf/json](https://github.com/taocpp/json/tree/main/src/perf/json).

How do I build it?
How do I run it?

**Comment by ColinH** [comment]
These are microbenchmarks that we used during early development. They aren't really intended for end-users. That said:

When you build with `make` the performance test binaries are automatically built, too. If you build with Cmake then ... the easiest way is probably to move them to `src/example/json` and modify the `CMakeLists.txt` file accordingly.

Most of the benchmarks need to be called in the shell with a (large) JSON file, like the ones in the `tests` directery, to do their thing.

**Comment by toughengineer** [comment]
Do you plan to provide a way to build existing benchmarks with CMake out of the box? Or add new benchmarks?

I have an idea how to make parsing of JSON faster and wanted to experiment. I would like to use common reference point in the form of benchmarks already set up to be built instead of (everybody) inventing their own way.

**Comment by ColinH** [comment]
There are no current plans in that direction. Did you manage to build (and run) the benchmarks?

**Comment by toughengineer** [comment]
I did not try to build it, I guess I will maybe come back to it some other time.

The idea I wanted to experiment with is to parse first small number of JSON array elements (say, 42) into an array (e.g. `std::array` or plain C-style array, without memory (re)allocation) eventually moving them into the array storage in the value, and only then use `push_back`/`emplace_back`. First few `push_back`s are relatively expensive so temporarily putting parsed elements into an array offsets this cost and makes parsing noticeably faster.

**Comment by ColinH** [comment]
I just committed an update to the Cmake configuration that also builds the perf applications. If I remember correctly the only reason to exclude them was that the timing code used to be partially platform dependent, but it has since been changed to use `std::chrono` and should compile everywhere.

**Comment by ColinH** [comment]
Even assuming that you will be using a bulk insert into the vector, you are still copying the elements around and I wonder whether it wouldn't be more efficient to just call `reserve()` on it before starting to `emplace_back()` elements. Should be easy to add to the `tao::json::events::set_basic_value::begin_array()` Events method; the one that takes a `std::size_t` already does just that.

**Comment by ColinH** [comment]
Yes, the trade-off between time and space, as old as computer programming ;-)
