### ISSUE TITLE
Why checking Type equals 0

### ISSUE THREAD

**Issue by XinyuHou** [taocpp/json#15]
https://github.com/taocpp/json/blob/master/include/tao/json/traits.hpp#L33

In traits, line 33, there is a static assert to check if type size equals 0. Why?

**Comment by d-frey** [comment]
Because it should never be necessary to instantiate the base template. As the `static_assert` error message says, you need to specialize the traits for each type you are using.

Using `sizeof(T)==0` is a trick to make the line depend on the template parameter and which always yields `false` (since no type can have a size of 0), so you get a nice compile-time error message when you instantiate (aka use) the template with a type without specializing it first. If I would just write `static_assert( false, "..." );`, the error would appear immediately when compiling the template itself. The error must be deferred until it is instantiated, hence the dependency on a template parameter is required.

**Comment by XinyuHou** [comment]
We experienced this issue when trying to use the library with MSVC 2015. Everything seems to work fine, but this assertion is triggered. We definitely can't be using the traits::assign() function though, since surely that would generate a link time error?

**Comment by d-frey** [comment]
If the assert triggers, it means you forgot to specialize the traits function. Look at the error message, what it `T`? (The compiler will usually tell you)

That is the type you are trying to use, but there is no traits specialization for that type, hence the library doesn't know what to do with it. The `static_assert` *must* trigger to notify you of a problem in your code.

If you can post the error message and a small code example/excerpt, I might be able to help further...

**Comment by XinyuHou** [comment]
> what it T? (The compiler will usually tell you)

The visual studio compiler is not giving us any useful information.

I commented out all the code that uses your lib but only include the header. The compile output is 

`
c:\projects\app\third_party\json\include\tao\json\traits.hpp(32): error C2338: no traits specialization found
c:\projects\app\third_party\json\include\tao\json/value.hpp(118): note: see reference to class template instantiation 'tao::json::traits<std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const _Kty,_Ty>>>>,void>' being compiled
        with
        [
            _Kty=std::string,
            _Ty=tao::json::basic_value<tao::json::traits>
        ]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xtree(1444): note: while compiling class template member function 'std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const _Kty,_Ty>>>> std::_Tree<std::_Tmap_traits<_Kty,_Ty,_Pr,_Alloc,false>>::erase(std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const _Kty,_Ty>>>>,std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const _Kty,_Ty>>>>)'
        with
        [
            _Kty=std::string,
            _Ty=tao::json::basic_value<tao::json::traits>,
            _Pr=std::less<std::string>,
            _Alloc=std::allocator<std::pair<const std::string,tao::json::basic_value<tao::json::traits>>>
        ]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xtree(2168): note: see reference to function template instantiation 'std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const _Kty,_Ty>>>> std::_Tree<std::_Tmap_traits<_Kty,_Ty,_Pr,_Alloc,false>>::erase(std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const _Kty,_Ty>>>>,std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const _Kty,_Ty>>>>)' being compiled
        with
        [
            _Kty=std::string,
            _Ty=tao::json::basic_value<tao::json::traits>,
            _Pr=std::less<std::string>,
            _Alloc=std::allocator<std::pair<const std::string,tao::json::basic_value<tao::json::traits>>>
        ]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\map(73): note: see reference to class template instantiation 'std::_Tree<std::_Tmap_traits<_Kty,_Ty,_Pr,_Alloc,false>>' being compiled
        with
        [
            _Kty=std::string,
            _Ty=tao::json::basic_value<tao::json::traits>,
            _Pr=std::less<std::string>,
            _Alloc=std::allocator<std::pair<const std::string,tao::json::basic_value<tao::json::traits>>>
        ]
c:\projects\app\third_party\json\include\tao\json/value.hpp(868): note: see reference to class template instantiation 'std::map<std::string,tao::json::basic_value<tao::json::traits>,std::less<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>>' being compiled
        with
        [
            _Kty=std::string,
            _Ty=tao::json::basic_value<tao::json::traits>
        ]
c:\projects\app\third_party\json\include\tao\json/from_string.hpp(78): note: see reference to class template instantiation 'tao::json::basic_value<tao::json::traits>' being compiled`

**Comment by d-frey** [comment]
Ah, I see. Well, the error message is basically complaining about a missing specialization for

    std::map< std::string, tao::json::basic_value< tao::json::traits > >::const_iterator

but that is most likely a problem in our code. As we are not Visual Studio / Windows users ourselves and the library is in an early stage of development, we haven't found the time to make it compatible with Visual Studio. I know, bad news... sorry.

I am about to refactor some more stuff (probably later today), maybe it solves the problem, maybe not. Probably not. :-/ Anyways, I'm afraid there is no real solution currently. After the next refactoring, we would, of course, appreciate help from actual Visual Studio users if they can figure out ways to fix the problems VS is having and send a pull request. I'll close the question for now, general Visual Studio / Windows support will happen anyways when we have enough time and help in the future.

**Comment by XinyuHou** [comment]
Sure, thank you very much for all the help. Enjoy coding :D
