### ISSUE TITLE
invalid unescaped character

### ISSUE THREAD

**Issue by gazzatav** [taocpp/json#154]
Using taocpp-json/1.0.0-beta.14 as a package from conan v2.
Ubuntu 22.04

I'm working on a client that queries a tidal database for water levels and I'm noticing that in my debug output I am seeing this hitherto unseen exception - here is the end of the output:

 ```
 , { 
    "@id" : "http://environment.data.gov.uk/flood-monitoring/data/readings/720763-level-tidal_level-Mean-15_min-m/2024-10-08T13-30-00Z" ,
    "dateTime" : "2024-10-08T13:30:00Z" ,
    "measure" : "http://environment.data.gov.uk/flood-monitoring/id/measures/720763-level-tidal_level-Mean-15_min-m" ,
    "value" : 3.66
  }
  , { 
    "@id" : "http://environment.data.gov.uk/flood-monitoring/data/readings/720763-level-tidal_level-Mean-15_min-m/2024-10-08T12-30-00Z" ,
    "dateTime" : "2024-10-08T12:30:00Z" ,
    "measur
terminate called after throwing an instance of 'tao::pegtl::parse_error'
  what():  tao::json::events::from_string:286:12: invalid unescaped character
Aborted (core dumped)
```

In the output the next character would have been 'e'.  I realise that this could be due to server (which is currently being worked on) but I would be grateful for any insight or advice on how to track down what is going on and how to deal with this. The output shown is just my debug output and the end of the response may not be where the exception was thrown.

**Comment by ColinH** [comment]
When you say "the next character would have been an `e`, does that  mean the `e` was part of the input but somehow not parsed, or that it was missing from the input even though the word was obviously supposed to be `measure`? If the input ended with `"measur` then this might just be a case of inaccurate error message, which I'll verify later.

**Comment by gazzatav** [comment]
@ColinH Thanks for the reply.  If the server that replied is working correctly I believe that somewhere in a socket buffer or a response buffer is the next 'e'.  I have told the buffer to transfer an exact number of bytes according to what the chunk length is.  However the response can be tens of kilobytes.  I may be handling multiple chunks incorrectly so that I have only transferred the first chunk for example.  That would explain why the input to the 'from_string' function runs short.  In that case I would have expected an error something along the lines of 'malformed json, expected }' rather than 'invalid escape character'.

**Comment by ColinH** [comment]
Just checked this, the error message is bogus, it should say "unterminated string" rather than "invalid escape character". That's one of the reasons we aren't at 1.0.0 yet, everything works well and is stable, but good error messages require a lot of additional effort.

**Comment by gazzatav** [comment]
@ColinH  Thanks for checking that.  I can close this issue now or leave it open till it's fixed.  I expect you'll want to close this issue leave it as a task for later as it's not critical and people can find what it should say by searching here.  Thanks for all your work and I totally get that about good error messages - and then there's all the documentation :)
