### ISSUE TITLE
parse wrong with signed

### ISSUE THREAD

**Issue by Kurt-Shiwz** [taocpp/json#16]
```c++
std::string tt = "{\"test_s\": \"straaaa\", \"test_i\": 5, \"test_d\": 123.456}";
tao::json::custom_value v = tao::json::custom_from_string(tt.c_str());
// after parse test_i is unsigned, use get_signed can't get the value
std::cout << v["test_i"].get_unsigned() << std::endl;
// if i use get_unsigned and stored in signed int, it also work
// int a = v.["test_i"].get_unsigned();
// std::cout << a << std::endl;
// if i reset with int(yes it is signed int), v["test_i"] became singned, get_signed will work
v["test_i"] = 111;
std::cout << v["test_i"].get_signed() << std::endl;
```
if parse from string can't distinguish it is signed or unsigned, should get_unsigned and get_signed can both work? 

if that the code look more unified
```c++
int a = v.["test_i"].get_signed();
std::cout << a << std::endl;
v["test_i"] = 111;
std::cout << v["test_i"].get_signed() << std::endl;
// unsigned int a = v.["test_i"].get_unsigned();
// std::cout << a << std::endl;
// v["test_i"] = 111u;
// std::cout << v["test_i"].get_unsigned() << std::endl;
```

judge
--

**Comment by d-frey** [comment]
You are looking at the wrong interface :)

`get_signed` and `get_unsigned` are low-level accessors and reflect the fact, that internally we store signed and unsigned integer values as different types.

If you want to extract a number, you should use `as< ... >()` which forwards to the traits class template. The traits class template is then responsible for how to handle overflows - unchecked casting, check & throw or check & assert... - the default is currently unchecked casting.

**Comment by Kurt-Shiwz** [comment]
thank you, it worked
