### ISSUE TITLE
Failure to compile under clang 6.0

### ISSUE THREAD

**Issue by nadiasvertex** [taocpp/json#19]
Beta 9 release fails to compile under clang 6.0.

clang++-6.0 --version
clang version 6.0.0-svn321433-1~exp1 (trunk)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

```
[10/76] Building CXX object src/test/json/CMakeFiles/ostream.dir/ostream.cpp.o
FAILED: /usr/bin/clang++-6.0    -I/home/csnelson/meps/projects/mf/toolchain/tao-json-1.0.0-beta.9/include -g   -pedantic -Wall -Wextra -Wshadow -Werror -std=c++11 -MMD -MT src/test/json/CMakeFiles/ostream.dir/ostream.cpp.o -MF src/test/json/CMakeFiles/ostream.dir/ostream.cpp.o.d -o src/test/json/CMakeFiles/ostream.dir/ostream.cpp.o -c /home/csnelson/meps/projects/mf/toolchain/tao-json-1.0.0-beta.9/src/test/json/ostream.cpp
In file included from /home/csnelson/meps/projects/mf/toolchain/tao-json-1.0.0-beta.9/src/test/json/ostream.cpp:6:
/home/csnelson/meps/projects/mf/toolchain/tao-json-1.0.0-beta.9/include/tao/json/stream.hpp:25:51: error: result of comparison 'std::uint64_t' (aka 'unsigned long') > 18446744073709551615 is always false [-Werror,-Wtautological-constant-compare]
            if( static_cast< std::uint64_t >( w ) > static_cast< std::uint64_t >( std::numeric_limits< std::size_t >::max() ) ) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by nadiasvertex** [comment]
After looking at the code, the check doesn't make much sense. width() is generally gonna return a signed size_t value. It will never be larger than uint64_t. You could check to see if it's less than 0, but otherwise I'm not really sure what you are checking here.

**Comment by d-frey** [comment]
I was trying to shut up Visual Studio in 32 bit mode where`std::size_t` is 32 bits, but `w` could potentially be larger, although in practice that makes no sense. It's now the usual dance to keep three compilers in both 32 and 64 bit mode happy, all using extremely high warning levels... 🤔

**Comment by d-frey** [comment]
I guess limiting the indention to 256 should be enough for any reasonable real-world use-case and it might even catch errors if someone really messed up and sets the width to, say, a million spaces or something... plus the code will be much clearer...
