### ISSUE TITLE
struct element2 template compile error

### ISSUE THREAD

**Issue by Sereglaith** [taocpp/json#23]
I updated to the latest commit, and I have encountered a compilation issue.
I am running gcc version (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609.

I use a CMake file to build my program, and I have the following set:
cmake_minimum_required(VERSION 3.10)
set(CMAKE_CXX_STANDARD 11)

I primarily use the JAXN interface with events and to/from_string() functions.

After removing the following code in element.hpp (lines 97-129), I am once again able to compile.

         template< typename C, typename T, T ( *P )( const C& ), typename U, U( *Q )( C& ) >
         struct element2< T ( * )( const C& ), P, U ( * )( C& ), Q >
         {
            static auto read( const C& v ) -> decltype( P( v ) )
            {
               return P( v );
            }

            template< typename W >
            static void write( C& v, W&& w )
            {
               Q( v ) = std::forward< W >( w );
            }

            template< template< typename... > class Traits, typename Base >
            static void as( const basic_value< Traits, Base >& v, C& x )
            {
               v.as( Q( x ) );
            }

            template< template< typename... > class Traits = traits, typename Producer >
            static void consume( Producer& parser, C& v )
            {
               json::consume< Traits >( parser, Q( v ) );
            }

            template< template< typename... > class Traits = traits, typename Consumer >
            static void produce( Consumer& consumer, const C& v )
            {
               events::produce< Traits >( consumer, P( v ) );
            }
        };

Here is the full set of compile errors:

```
/home/user/src/crypto_profiteer/json/include/tao/json/binding/element.hpp:98:81: error: expected identifier before ‘*’ token
          template< typename C, typename T, T ( *P )( const C& ), typename U, U( *Q )( C& ) >
                                                                                 ^
/home/user/src/crypto_profiteer/json/include/tao/json/binding/element.hpp:99:61: error: wrong number of template arguments (3, should be at least 4)
          struct element2< T ( * )( const C& ), P, U ( * )( C& ), Q >
                                                             ^
/home/user/src/crypto_profiteer/json/include/tao/json/binding/element.hpp:96:17: note: provided for ‘template<class T, T <anonymous>, class U, U <anonymous>, class> struct tao::json::binding::element2’
          struct element2;
                 ^
/home/user/src/crypto_profiteer/json/include/tao/json/binding/element.hpp:99:63: error: expected unqualified-id before ‘)’ token
          struct element2< T ( * )( const C& ), P, U ( * )( C& ), Q >
                                                               ^
/home/user/src/crypto_profiteer/json/include/tao/json/binding/element.hpp:98:81: error: expected identifier before ‘*’ token
          template< typename C, typename T, T ( *P )( const C& ), typename U, U( *Q )( C& ) >
                                                                                 ^
/home/user/src/crypto_profiteer/json/include/tao/json/binding/element.hpp:99:61: error: wrong number of template arguments (3, should be at least 4)
          struct element2< T ( * )( const C& ), P, U ( * )( C& ), Q >
                                                             ^
/home/user/src/crypto_profiteer/json/include/tao/json/binding/element.hpp:96:17: note: provided for ‘template<class T, T <anonymous>, class U, U <anonymous>, class> struct tao::json::binding::element2’
          struct element2;
                 ^
/home/user/src/crypto_profiteer/json/include/tao/json/binding/element.hpp:99:63: error: expected unqualified-id before ‘)’ token
          struct element2< T ( * )( const C& ), P, U ( * )( C& ), Q >
                                                               ^
/home/user/src/crypto_profiteer/json/include/tao/json/binding/element.hpp:98:81: error: expected identifier before ‘*’ token
          template< typename C, typename T, T ( *P )( const C& ), typename U, U( *Q )( C& ) >
                                                                                 ^
/home/user/src/crypto_profiteer/json/include/tao/json/binding/element.hpp:99:61: error: wrong number of template arguments (3, should be at least 4)
          struct element2< T ( * )( const C& ), P, U ( * )( C& ), Q >
                                                             ^
/home/user/src/crypto_profiteer/json/include/tao/json/binding/element.hpp:96:17: note: provided for ‘template<class T, T <anonymous>, class U, U <anonymous>, class> struct tao::json::binding::element2’
          struct element2;
                 ^
/home/user/src/crypto_profiteer/json/include/tao/json/binding/element.hpp:99:63: error: expected unqualified-id before ‘)’ token
          struct element2< T ( * )( const C& ), P, U ( * )( C& ), Q >
                                                               ^
/home/user/src/crypto_profiteer/json/include/tao/json/binding/element.hpp:98:81: error: expected identifier before ‘*’ token
          template< typename C, typename T, T ( *P )( const C& ), typename U, U( *Q )( C& ) >
                                                                                 ^
/home/user/src/crypto_profiteer/json/include/tao/json/binding/element.hpp:99:61: error: wrong number of template arguments (3, should be at least 4)
          struct element2< T ( * )( const C& ), P, U ( * )( C& ), Q >
                                                             ^
/home/user/src/crypto_profiteer/json/include/tao/json/binding/element.hpp:96:17: note: provided for ‘template<class T, T <anonymous>, class U, U <anonymous>, class> struct tao::json::binding::element2’
          struct element2;
                 ^
/home/user/src/crypto_profiteer/json/include/tao/json/binding/element.hpp:99:63: error: expected unqualified-id before ‘)’ token
          struct element2< T ( * )( const C& ), P, U ( * )( C& ), Q >
                                                               ^
```

**Comment by d-frey** [comment]
I've tried a fix, could you update and try again, please?

**Comment by Sereglaith** [comment]
Still the same errors with the latest master.

**Comment by ColinH** [comment]
Is this while compiling the examples and tests included with the library, or is this while compiling your own code? Can you also show us the exact command line arguments that GCC is invoked with?

**Comment by ColinH** [comment]
Is it possible for you to test with GCC 5.5.0, which is the version included in the Ubuntu distributions that we are using?

**Comment by d-frey** [comment]
I also checked with my GCC 5.5 (on Ubuntu 18.04, fully upgraded), with only `-std=gnu++11 -g -Wall` and our tests, which contain a call to `element2`, but everything seems to compile and work fine.

But the hint you found (`-std=gnu++11`) makes sense to me: It seems the compiler is getting confused at a very early level, maybe even at the syntax. I'm looking forward to see your example to reproduce the bug.

**Comment by Sereglaith** [comment]
Ok, I figured it out. Macros are EVIL! The cpprestsdk provided by Microsoft redefines U() for the purposes of doing their insane utf16/utf8 string definitions.  And of course the U in the class element template gets redefined accordingly.

I'll be dropping cpprestsdk soon since it has not been helpful.

Thanks for you time on this issue. Maybe for the next person who has to deal with this you might want to choose a different template argument name other than U.

Thanks for a great library, the more I use it, the happier I am with it!

**Comment by d-frey** [comment]
Wow. OK, so besides `min` and `max`, Microsoft now also reserves `U`. Whiskey. Tango. Foxtrot.

The real question is: What other names do we have to avoid in order to be portable? This is crazy. I'll check with Colin and see what we can do, maybe simple identifiers must be avoided in general?

Thanks anyways for reporting the problem and also reporting back on what caused it!
