### ISSUE TITLE
double.hpp: Add support for Windows ARM64

### ISSUE THREAD

**Issue by matbech** [taocpp/json#34]
double.hpp does not support Windows ARM64:
include\tao\json\external\double.hpp
#error Target architecture was not detected as supported by Double-Conversion.

It might be enough to add:
defined(_M_ARM64) 
to the if clause.

**Comment by ColinH** [comment]
That's a bummer. Often "modern" code just works on another architecture, but with double-conversion being more low-level than your average business logic I'm not quite convinced. However our tests should catch any issue, so we might as well just go with your suggestion. @d-frey can we test this somewhere?

**Comment by d-frey** [comment]
Do you really need Windows ARM64 or just any ARM64? If it's the latter, check out taocpp/PEGTL and the Doozer Tests.

**Comment by matbech** [comment]
@d-frey Yes, Windows ARM64.

**Comment by ColinH** [comment]
@matbech Ok, even though we can't test it, if you want to submit a PR we'll accept it, and we'll rely on the tests catching any possible issues.

**Comment by matbech** [comment]
PR: https://github.com/taocpp/json/pull/35
Thanks

**Comment by ColinH** [comment]
Great, thanks, merged.
