### ISSUE TITLE
Assigning to boost::optional<tao::json::value> doesn't compile anymore

### ISSUE THREAD

**Issue by bobkocisko** [taocpp/json#40]
I just switched to gcc-7.3 from gcc-5.4 and bumped up my taocpp::json version from beta.8 to beta.11.  The following assignment no longer works.  Any thoughts?

```c++
  boost::optional<tao::json::value> bov;
  bov = boost::none;
```

The error is
```
/taojson/include/tao/json/basic_value.hpp:78:81: error: incomplete type ‘tao::json::traits<boost::none_t>’ used in nested name specifier
             noexcept( noexcept( Traits< typename std::decay< T >::type >::assign( std::declval< basic_value& >(), std::forward< T >( v ) ) ) )
```

**Comment by bobkocisko** [comment]
Oh, I also switched from boost 1.58 to 1.68.  This is probably more the issue because when I reverted back to gcc-5.4 and beta.8 but still using boost 1.68, I have the same problem.

**Comment by d-frey** [comment]
The same problem occurred with `std::optional`. I think I found the problem and fixed it, please test and re-open the issue if the problem still remains for `boost::optional`.
