### ISSUE TITLE
Instantiate value from map<string,string> and compare to value<traits>

### ISSUE THREAD

**Issue by mallexxx** [taocpp/json#45]
I'm must be missing something very obvious, but can't figure out how to correctly initialise json::value from std::map<std::string, std::string> and then compare to value parsed from string.

Value from map seems working if I add my_traits from std::map<string,string> similarly to https://github.com/taocpp/json/issues/12 but then I need to compare the result to existing value parsed from string:
`auto expected = tao::json::from_string(expectedData);
tao::json::basic_value< my_traits > w( map );
EXPECT(expected == w)
`
This gives me an error: Invalid operands to binary expression ('const tao::json::basic_value<traits>::array_t' (aka 'const vector<tao::json::basic_value<traits> >') and 'const tao::json::basic_value<my_traits>::array_t' (aka 'const vector<tao::json::basic_value<my_traits> >'))

**Comment by ColinH** [comment]
Just tested the following code, it compiles, and the assertions pass.

```c++
#include <cassert>
#include <tao/json.hpp>
#include <tao/json/contrib/traits.hpp>

int main( int, char** )
{
   const std::map< std::string, std::string > m = { { "a", "b" }, { "c", "d" } };
   const tao::json::value v = m;
   const tao::json::value w = tao::json::from_string( "{\"a\":\"b\",\"c\":\"d\"}" );
   assert( v == w );
   assert( v == m );
   assert( w == m );
   return 0;
}
```

If this does *not* help you fix the issue, can you please show your complete source?

**Comment by mallexxx** [comment]
Yup!
Adding ```#include <tao/json/contrib/traits.hpp>``` solved the problem.
Thanks!
