### ISSUE TITLE
Getting several nodiscard errors

### ISSUE THREAD

**Issue by robinchrist** [taocpp/json#52]
Hi,
When compiling with MSVC, I get several errors because of nodiscard (`tao\json\external\pegtl\internal/duseltronik.hpp(140): warning C4834: Der Rückgabewert einer Funktion mit dem "nodiscard"-Attribut wird verworfen.`)

Line are
duseltronik.hpp(140)
duseltronik.hpp(89)

Full (example) trace:
https://pastebin.com/dvhspErc

**Comment by ColinH** [comment]
Looks like MSVC is a bit over-eager, it's complaining about the return "value" not being used although it's `void`. GCC and Clang seem to be smart enough to ignore `[[nodiscard]]` for `void` functions.

**Comment by ColinH** [comment]
Does sticking `(void)` in front of the two offending lines remove the warning, i.e. writing `(void)Control< Rule >...` instead of just `Control< Rule >...`?

**Comment by d-frey** [comment]
I'm missing something here... line 140 calls `apply0` and it is part of the specialization for when `apply0` returns `void`. So where is the `[[nodiscard]]` coming from that VS is complaining about? Or does `apply0` return `bool` (with `[[nodiscard]]`)? In that case, the **detection** of the return type could be broken.

**Comment by ColinH** [comment]
I was assuming that MSVC issued the warning for a `void`, which is why I asked @robinchrist to test with `(void)` at the beginning of the offending lines. Should we also test for broken detection? Assign to a new `bool` variable and then `(void)` that?

**Comment by robinchrist** [comment]
Sorry guys, was busy for the last few days. Gonna try what you suggested tomorrow!

**Comment by d-frey** [comment]
I just committed a small fix, please check if the error is still there after e022559aee05101ca8dd0e36852c58d8cbc452f3

**Comment by robinchrist** [comment]
@d-frey e022559 seems to fix this!

**Comment by d-frey** [comment]
Thanks for confirming!
