### ISSUE TITLE
Calculate JSON Value string representation size

### ISSUE THREAD

**Issue by SergeyVasiliev** [taocpp/json#66]
Is there any way to calculate serialized to string JSON Value size without doing actual serialization?
If not, what is the right way to do it?

**Comment by d-frey** [comment]
We don't have anything in our toolbox right now, but you could write a consumer that calculates and adds the individual sizes of each element. Which obviously depends on the exact serialization you have in mind, e.g. whether you want to pretty-print or dense output.

**Comment by ColinH** [comment]
And, if possible, please show us your solution if you implement one!

**Comment by SergeyVasiliev** [comment]
Sure, here is what I have right now.
Note: I'm using taocpp-json 1.0.0-beta.10 because I'm stuck with c++11 compiler.
[to_string_size_calc.diff.txt](https://github.com/taocpp/json/files/3763659/to_string_size_calc.diff.txt)

**Comment by ColinH** [comment]
Thank you, now that you have a solution up-and-running we won't add anything at this point, mostly because there are other parts that we are currently working on, but as always we are ready to re-visit any addition when there is more demand, in which case we could add something to contrib.
