### ISSUE TITLE
MSVC: error C2607: static assertion failed

### ISSUE THREAD

**Issue by matbech** [taocpp/json#67]
With MSVC 2019 16.4 Preview 4
taocpp-json\json\include\tao\json\basic_value.hpp(68,1): error C2607: static assertion failed 

      static_assert( std::is_nothrow_move_assignable_v< variant_t > );

I believe it started since this commit:
https://github.com/taocpp/json/commit/cc69b1daf2aa4f322f5db6160d861878eea8280a

**Comment by d-frey** [comment]
Yeah, should be fixed now.

For the record: If I am ever going to develop my own language I will enforce nothrow move construction, nothrow move assignment, nothrow destruction and nothrow swap. Damnit! 😤
