### ISSUE TITLE
fwd decleration of tao::json::value

### ISSUE THREAD

**Issue by assafcohen** [taocpp/json#70]
Hi,
I have a class with pure virtual function:
`
#include <tao/json/value.hpp>
class ab{
      [[nodiscard]] virtual std::shared_ptr<action_msg> get_message(const tao::json::value & v) const = 0;
};
` 
I would like a way to forward declare ` tao::json::value` and get rid of the include.
Is there such a way?
Thanks

**Comment by ColinH** [comment]
Right, there's `tao/include/forward.hpp`, but that only forward declares `tao::json::traits` and `tao::json::basic_value`, but not `tao::json::value`, which is in `tao/include/value.hpp`. For now you could replicate the declarations and we'll see whether we can't make `forward.hpp` more complete and self-contained.

**Comment by ColinH** [comment]
Actually, see whether this does the job, `forward.hpp` is now self-contained, i.e. does not include anything else, and also declares `value`.

**Comment by ColinH** [comment]
I'm assuming this issue is resolved with the aforementioned commit, feel free to comment here and/or reopen if anything doesn't work or needs clarification.

**Comment by assafcohen** [comment]
Thanks works gr8
