### ISSUE TITLE
unordered_set type trait does not work because try_emplace is not a method of unordered_set

### ISSUE THREAD

**Issue by fteicht** [taocpp/json#76]
The following line does not compile:
`tao::json::value v = std::unordered_set<std::vector<bool>>({{false, true}, {true, false}});`

The compiler (g++-9) returns the following error: `'class std::unordered_set<std::vector<bool> >' has no member named 'try_emplace'; did you mean 'emplace'?`

Indeed, I think there is a bug [here](https://github.com/taocpp/json/blob/d8060a62082dbcc024b1c48751606055cdcddcc5/include/tao/json/contrib/unordered_set_traits.hpp#L25) and [there](https://github.com/taocpp/json/blob/d8060a62082dbcc024b1c48751606055cdcddcc5/include/tao/json/contrib/unordered_set_traits.hpp#L34).

Obviously, by nature of unordered sets, there is no `try_emplace` method in [unordered_set](https://en.cppreference.com/w/cpp/container/unordered_set).

Thanks!

**Comment by fteicht** [comment]
Then, when I replace `try_emplace` by just `emplace` [here](https://github.com/taocpp/json/blob/d8060a62082dbcc024b1c48751606055cdcddcc5/include/tao/json/contrib/unordered_set_traits.hpp#L25), I get another error: `'as' is not a member of 'tao::json::traits<std::vector<bool> >'`

Indeed, when I explore the hierarchy of the specialised class [`traits< std::vector< bool > >`](https://github.com/taocpp/json/blob/d8060a62082dbcc024b1c48751606055cdcddcc5/include/tao/json/contrib/traits.hpp#L85) I cannot find any `as` method.

**Comment by ColinH** [comment]
Which top-level operation on a `json::value` is triggering the error with the `std::vector< bool >`?

**Comment by fteicht** [comment]
I found a working replacement: change [this line](https://github.com/taocpp/json/blob/ad7fa4379c6bbb3db52a0a5d7c4ea1465c111976/include/tao/json/contrib/unordered_set_traits.hpp#L25) with the following one:

`r.emplace( i.template as_with< T >( with... ) );`

I saw you just updated the repo - thank you for such a quick reaction! - but I think you should further take this modification into account to make it work. Thanks a lot Colin!

**Comment by fteicht** [comment]
> Which top-level operation on a `json::value` is triggering the error with the `std::vector< bool >`?

Just this line of code:
`The following line does not compile:
tao::json::value v = std::unordered_set<std::vector<bool>>({{false, true}, {true, false}});`

But again, my previous comment solves the issue so perhaps you may want to implement this change. I just took inspiration from your own implementation of vector traits.

**Comment by ColinH** [comment]
Ok, got it.

The `traits` specialisations frequently only need to implement one of `as()` and `to()` because `basic_value::as()` and `basic_value::to()` are implemented to use "anything" that is available if possible.

However the specialisation that you just showed how to fix directly called `as()` on the traits, and therefore did not work when only `to()` is available, and the fix is of course to go through the `basic_value`, just like all the other traits do.

Thanks.
