### ISSUE TITLE
Apple/clang crash with openmp and tao::json::value

### ISSUE THREAD

**Issue by fteicht** [taocpp/json#79]
Hi,

The following minimal code crashes the Apple/clang compiler in openmp mode:

```
#include <unordered_set>
#include <vector>
#include <json.hpp>
#include <json/contrib/traits.hpp>

int main() {
    // tao::json::value v = {{true, true}, {false, false}}; // compilation error (fine)
    tao::json::value v = std::unordered_set<std::vector<bool>>({{true, true}, {false, false}}); // compiler crash (bug)
    return 0;
}
```

Obviously, openmp is not needed in this minimal code, but this bug prevents me from using tao::json within a code that needs openmp parallelization.
The compilation line is:
`clang++ -std=c++17 -Xclang -fopenmp -I<path-to-tao-json-include-dir> test.cc`
My compiler is the following:

```
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

The compiler output is:

```
clang: error: unable to execute command: Illegal instruction: 4
clang: error: clang frontend command failed due to signal (use -v to see invocation)
```

Thanks in advance!
Florent

**Comment by ColinH** [comment]
It seems to work for me with Apple Clang 11, possibly a bug in the older Clang you are using? Can you update to the latest Xcode and Clang?
```sh
colin@magic:~/Taocpp/json> git pull
Already up to date.
colin@magic:~/Taocpp/json> cd /tmp/ramdisk/
colin@magic:/tmp/ramdisk> cat test.cc 
#include <unordered_set>
#include <vector>
#include <json.hpp>
#include <json/contrib/traits.hpp>

int main() {
    // tao::json::value v = {{true, true}, {false, false}}; // compilation error (fine)
    tao::json::value v = std::unordered_set<std::vector<bool>>({{true, true}, {false, false}}); // compiler crash (bug)
    return 0;
}
colin@magic:/tmp/ramdisk> clang++ -std=c++17 -Xclang -I/Users/colin/Taocpp/json/include/tao test.cc
colin@magic:/tmp/ramdisk> clang++ -std=c++17 -Xclang -fopenmp -I/Users/colin/Taocpp/json/include/tao test.cc
colin@magic:/tmp/ramdisk> clang++ -v
Apple clang version 11.0.0 (clang-1100.0.33.16)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by fteicht** [comment]
Unfortunately I can't update to Apple Clang 11 because I am not the administrator of my Mac. It's at least good news if it works with the latest Apple Clang.

**Comment by ColinH** [comment]
Quite frankly I'm not quite sure what to do about this. You said it works on your compiler when not using OpenMP, so it might very well be some strange bug in the compiler triggered by the combination of OpenMP and modern C++. And on the newer compiler it works with or without OpenMP. Does it work for you with OpenMP when you replace the always-tricky `std::vector< bool >` with a `std::vector< int >` or similar?

**Comment by fteicht** [comment]
You're right, it sounds like a compiler bug but I thought there was maybe a way to slightly adapt your code so it can work with most C++17 compliant existing compilers (assuming we can find the problematic lines of code which I could not).
I tried to replace std::vector<bool> with std::vector<int> but this time it does not compile because there is no default hash function for std::vector<int>.

**Comment by fteicht** [comment]
Update: I provided a stupid hasher for std::vector<int> :
```
struct Hasher {
    std::size_t operator()(const std::vector<int>& v) const {
        return 0;
    }
};

int main() {
    // tao::json::value v = {{true, true}, {false, false}}; // compilation error (fine)
    tao::json::value v = std::unordered_set<std::vector<int>, Hasher>({{1, 1}, {0, 0}}); // compiler crash (bug)
    return 0;
}
```
... and I still get the same compiler crash.

**Comment by ColinH** [comment]
You're on macOS 10.14 with Xcode 10?

**Comment by fteicht** [comment]
Yes exactly.

**Comment by ColinH** [comment]
Unfortunately I've got access to a new Mac with 10.15, and an old one that doesn't get past 10.13. And since it's a very special case that also works with the current compiler there's not that much incentive to spend a lot of time on it. If you find a work-around we'll consider including it. Sorry for not being of more help, good luck!

**Comment by ColinH** [comment]
Have you managed to find a work-around and/or upgrade to the current compiler where your code seems to work? Sorry we couldn't be of more help.
