### ISSUE TITLE
Conflicting tao::demangle()

### ISSUE THREAD

**Issue by le-migou** [taocpp/json#83]
When using both `tao::json` and `tao::pegtl`, one get a redefinition of `tao::demangle()`. This is because `tao::json` is bundled with a copy of `tao::pegtl` with different include guards. I don't really know what is the best course of action here. 

Using only the `pegtl` version shipped with `json` would break my modules dependency graph.

Would you be willing to consider giving us the option to use `tao::pegtl` in `json` instead of the bundled one? Knowing that the two are rigorously identical, modulo the `TAO_` macros names.

**Comment by le-migou** [comment]
Another option would be to take `tao::demangle()` out of `pegtl` and make it a standalone thing.

**Comment by d-frey** [comment]
It's a known problem, complicated by the fact that dependencies are still a PITA in C++. Ideally, taoJSON should simply depend on the PEGTL instead of bundling its own copy.

That said, I will give the `demangle`-issue some more thought. In the meantime, you could try the same solution I'm using: Drop the PEGTL itself and only use the version bundled with taoJSON. You can add `namespace tao { namespace pegtl = json::pegtl; }` to your code to normalize the usage of PEGTL.

**Comment by d-frey** [comment]
I've given it more thought and also discussed it with @ColinH, but there is no easy solution that we could agree on - only hacks. The real solution is to remove the embedded PEGTL from taoJSON and create a dependency in CMake. Currently, this would also mean adapting the Makefile (for people not using CMake), but long term CMake will be the "official" build system.

I'm currently working on the PEGTL's CI system to switch everything to GitHub Actions and using CMake for all CI jobs. Once that has been done, I will try and move all other projects of The Art of C++ to GitHub Actions and CMake. Once that is working, we need to tackle the dependency. 

In the meantime I hope the temporary solution I outlined in the previous comment works for you.

**Comment by d-frey** [comment]
There was another issue with `demangle()`, so I updated it in the PEGTL and also here in taoJSON. Can you check if the problem still persists for you? (Note: I move `tao::demangle()` to `tao::json::pegtl::demangle()`.

**Comment by le-migou** [comment]
It works like a charm, thanks.
