### ISSUE TITLE
Parser issue with closing brackets

### ISSUE THREAD

**Issue by VisualDevelopment** [taocpp/json#84]
### Expected behavior:
Not throw an error when you have a new line before the root closing bracket and after an array closing bracket

### Actual behavior:
Throws parser error.

### Example
```
{
    "Field1": "test",
    "Field2": [
        "test1",
        "test2"
    ]
}
```
Works if you change this to
```
{
    "Field1": "test",
    "Field2": [
        "test1",
        "test2"
    ]}
```
Or remove Field2 entirely
(I'm using tao::json::consume_string if that makes a difference)

### Version
master branch, commit fe2b4d1

**Comment by ColinH** [comment]
Can you give us the source of your program, or at least how `consume_string()` is called and the `traits` specialisations for the type of the object that is created from the JSON input?

**Comment by VisualDevelopment** [comment]
Sure!
```cpp
// Traits
struct Config {
    std::string outputFile;
};

namespace tao {
    template<>
    struct json::traits<Config> : public json::binding::basic_object<json::binding::for_unknown_key::skip,
                                      json::binding::for_nothing_value::encode,
                                      TAO_JSON_BIND_REQUIRED("OutputFile", &Config::outputFile)> {};
}    // namespace tao

// Logic
auto config = tao::json::consume_string<Config>(configStr); // configStr is the JSON file contents (I'm doing some processing to it before giving it, else I would use consume_file)
```

**Comment by VisualDevelopment** [comment]
Oh, and the error it gives is this
```
consume_string:28:6: parse error matching tao::json::pegtl::ascii::one<','>
```

**Comment by ColinH** [comment]
Right, I've replicated the same error and will see what's going on. (Of course with the "fixed" JSON there's still an error, but it's that the input did not contain something for the `"OutputFile"` binding, which is actually an error in the input file.)

**Comment by VisualDevelopment** [comment]
The example JSON I gave does not relate to the one my tool is using, rather it only replicates the problem.

**Comment by ColinH** [comment]
Problem is fixed in latest commit. We recently changed our `value` grammar to not include right-padding with white-space, but we forgot to add the padding back in the parts-parsers where it is needed, that's why it barfed when there were additional spaces or newlines after the skipped array value.

**Comment by VisualDevelopment** [comment]
I see. Thanks for your time by the way. Your library is awesome and your response time was really fast as well!

**Comment by ColinH** [comment]
Btw, you write "I'm using tao::json::consume_string if that makes a difference", and yes, that makes a huge difference and was essential information to quickly track down the bug.

**Comment by ColinH** [comment]
Thank you for your kind words, we are happy the library is useful!

**Comment by VisualDevelopment** [comment]
Oh wow! Well thought out, me. Also, I can confirm the issue is fixed. Thanks and have a nice day!
